job('First-Maven-Project-Via-DSL){
	description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven Project hosted on github")
	scm{
		git("https://github.com/sspradhan8055/Jenkin_Upgradev3.git", main)
	}
	triggers {
		scm('* * * * *')
	}
	steps {
		maven('clean package','pom.xml')
	}
	publishers {
		archiveArtifacts '**/*.war'
	}
}
